cc_binary(
    name = "hello-b",
    deps = ["//auth-server/hello:hello"]
)

cc_binary(
    name = "grades-b",
    deps = ["//auth-server/grades:grades"]
)

cc_binary(
    name = "quartiles-b",
    deps = ["//auth-server/quartiles:quartiles"]
)

cc_binary(
    name = "string-length-b",
    deps = ["//auth-server/string-length:string-length"]
)

cc_binary(
    name = "word-counter-b",
    deps = ["//auth-server/word-counter:word-counter"]
)
